import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "@/providers";
import Home from "./page";
import HeroSlider from "./(home)/HeroSlider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ShopXYZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" transition-all" data-theme="dark">
      <body className={inter.className}>
        <Providers>
          <div className=" flex min-h-screen flex-col justify-between">
            <Navbar></Navbar>

            {children}
            <Footer></Footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
